---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-home
  labels:
    app: fe-home
  namespace: fe-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-home
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fe-home
    spec:
      imagePullSecrets:
      - name: registry
      containers:
      - name: fe-home
        image: git.edenfarm.id:5050/project-version3/erp-dashboard/home/dev:<VERSION>
        ports:
          - name: http-port
            containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: 150Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 300m
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Jakarta
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: svc-fe-home
  namespace: fe-home
  labels:
    app: fe-home
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-port
  selector:
    app: fe-home
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-fe-home
  namespace: fe-home
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fe-home
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fe-home
  namespace: fe-home
spec:
  dnsNames:
    - fe-home.edenfarm.tech
  secretName: fe-home-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: fe-home
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: fe-home
spec:
  tls:
  - hosts:
    - fe-home.edenfarm.tech
    secretName: fe-home-tls
  rules:
  - host: fe-home.edenfarm.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-fe-home
            port:
              number: 80
